import { Montserrat } from 'next/font/google';
import './globals.css';
import { AppWrapper } from '@/context';

const inter = Montserrat({
  subsets: ['latin'],
  weight: ['400', '800'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <AppWrapper>
        <body className={inter.className}>{children}</body>
      </AppWrapper>
    </html>
  );
}
